### PR TITLE
fix: Make optional parameters to be optional

### LINKED ISSUE #92: fix: Make optional parameters optional
Currently, the following optional parameters are not truly optional: `s/` and `r/`

This issue was created to fix this issue

### PR DESCRIPTION
**Pull request by HarishB99**
Resolves #92

### CODE REVIEW

**Review by Zonnie-23 — APPROVED** [review]
LGTM

File: src/test/java/seedu/address/logic/parser/AddCommandParserTest.java [hunk 1]
```diff
@@ -162,6 +170,66 @@ public void parse_optionalFieldsMissing_success() {
...
+                .withEmail(VALID_EMAIL_AMY).withAddress(VALID_ADDRESS_AMY)
+                .withJobTitle(VALID_JOBTITLE_AMY).withLabel(VALID_LABEL_AMY)
+                .withTags(VALID_TAG_FRIEND)
+                .build();
+        assertParseSuccess(parser, NAME_DESC_AMY + PHONE_DESC_AMY + EMAIL_DESC_AMY + ADDRESS_DESC_AMY
+                        + JOBTITLE_DESC_AMY + LABEL_DESC_AMY + TAG_DESC_FRIEND,
+                new AddCommand(expectedPerson));
+
+        // zero tags, no remarks and no schedule
+        expectedPerson = new PersonBuilder(AMY).withTags().build();
```
Comment (Zonnie-23) [inline src/test/java/seedu/address/logic/parser/AddCommandParserTest.java:225]: Sorry, why is expectedPerson overwritten immediately after this?

Comment (HarishB99) [reply src/test/java/seedu/address/logic/parser/AddCommandParserTest.java:225]: Great catch! Line 225 should be removed. I will remove this later when I have time. Thank you!

Comment (HarishB99) [reply src/test/java/seedu/address/logic/parser/AddCommandParserTest.java]: I have removed the redundant line from the code. Thanks once again for pointing this out!

File: src/test/java/seedu/address/logic/parser/AddCommandParserTest.java [hunk 2]
```diff
@@ -162,6 +170,65 @@ public void parse_optionalFieldsMissing_success() {
...
+                new AddCommand(expectedPerson));
+
+        // zero tags, no remarks and no schedule
+        expectedPerson = new PersonBuilder().withName(VALID_NAME_AMY).withPhone(VALID_PHONE_AMY)
+                .withEmail(VALID_EMAIL_AMY).withAddress(VALID_ADDRESS_AMY)
+                .withJobTitle(VALID_JOBTITLE_AMY).withLabel(VALID_LABEL_AMY)
+                .build();
+        assertParseSuccess(parser, NAME_DESC_AMY + PHONE_DESC_AMY + EMAIL_DESC_AMY + ADDRESS_DESC_AMY
+                        + JOBTITLE_DESC_AMY + LABEL_DESC_AMY,
+                new AddCommand(expectedPerson));
```
Comment (ho-thanh-und) [inline src/test/java/seedu/address/logic/parser/AddCommandParserTest.java:231]: The comments helped to somewhat better understand each block of logic in this test method. Nice job!

**Review by ho-thanh-und — APPROVED** [review]
LGTM
