### PR TITLE
Bug view command

### LINKED ISSUE #120: Empty list / corrupted list will crash the program.
The current implementation of the view sidebar if the list of people is empty. Expected behaviour should be to just return a blank sidebar

### PR DESCRIPTION
**Pull request by Zonnie-23**
Fixes #120

### CODE REVIEW

File: src/main/java/seedu/address/logic/Logic.java [hunk 1]
```diff
@@ -43,6 +43,11 @@ public interface Logic {
      */
     GuiSettings getGuiSettings();
 
+    /**
+     * Returns the first person in the list, otherwise, if list is empty, return null
```
Comment (HarishB99) [inline src/main/java/seedu/address/logic/Logic.java:47]:
```suggestion
     * Returns the first person in the list; if list is empty, return null
```

**Comment by Zonnie-23** [comment]
> Looks good ! Just double checking that the null returned by getfirstperson on an empty list won't cause any errors right?

The null case is handles in the JobApplicationCard. But you raised a good point! I could technically wrap it in an optional wrapper and unwrap it at only at the end.

**Review by HarishB99 — APPROVED** [review]
Added one minor suggestion on one of the comments.

Otherwise, LGTM!
